file(GLOB_RECURSE APP_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/../*.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/../*.h"
    "${CMAKE_CURRENT_LIST_DIR}/../*.hpp"
)

list(FILTER APP_SOURCES EXCLUDE REGEX ".*/tests/.*")
list(FILTER APP_SOURCES EXCLUDE REGEX ".*/cmake/.*")
