get_filename_component(APP_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(APP_SRC_DIR "${APP_ROOT}/src")
set(APP_TESTS_DIR "${APP_ROOT}/tests")

file(GLOB_RECURSE APP_SOURCES CONFIGURE_DEPENDS
    "${APP_SRC_DIR}/*.cpp"
    "${APP_SRC_DIR}/*.h"
    "${APP_SRC_DIR}/*.hpp"
)

file(GLOB_RECURSE APP_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${APP_SRC_DIR}/*.cpp"
)

